services:
  #   mongodb:
  #     image: mongo:latest
  #     ports:
  #       - 27017:27017
  #     environment:
  #       - MONGO_INITDB_ROOT_USERNAME=root
  #       - MONGO_INITDB_DATABASE=auth
  #       - MONGO_INITDB_ROOT_PASSWORD=root
  #     volumes:
  #       - mongodb:/data/db
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    env_file:
      - .env
